[project]
name = "autoRunner"
version = "1.3.3"
description = "一个简单的自动化工具"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "opencv-python==4.11.0.86",
    "aircv==1.4.6",
    "pyautogui==0.9.53",
    "pillow==11.3.0",
]
